## **Pandas**

[Pandas](https://pandas.pydata.org/) is a popular Python library among data scientists with high performing, easy-to-use data structures and data analysis tools.

### **In this lesson you:**
- Explain what `pandas` is and why it's so popular
- Create and manipulate `pandas` `DataFrame` and `Series`
- Perform operations on `pandas` objects

First, let us import `pandas` with the alias `pd` so we can refer to the library without having to type `pandas` out each time. `pandas` is pre-installed ion Databricks.

In [ ]:
%pip install pandas
import pandas as pd

####  **Why `pandas`?**

* More and more, data is leading decision making.
* Excel is great but what if...
    * You want to automate your analysis so it re-runs on new data each day?
    * You want to build a code base to share with your colleagues?
    * You want more robust analyses to feed a business decision?
    * You want to machine learning?
* `pandas` is of the core libraries used by data analysts and data scientists in Python.

#####  **`DataFrame`**

We have seen now different data types provide different kinds of data and functionality.

`pandas` **is a library that provides data types and functions that allows us to do rigorous, programmatic data analysis.**
* The core `pandas` data type is called a `DataFrame`.

a [DataFrame](https://pandas.pydata.org/docs/reference/frame.html) is a two dimensional table of named rows and columns, similar to a SQL table.
* The `DataFrame` class has a `data` attribute for the data in the table that we have to define when we instantiate a `DataFrame` object.

Let's say we want to make the following table into a `DataFrame`:

| Name | Age | Job        |
| ---- | --- | ---------- |
| John | 30  | Journalist |
| Mary | 30  | Programmer |
| Abe  | 40  | Chef       |

One way to do this is to create a list of lists where each list in the list represents a row of data:

In [3]:
data = [["John", 30, "Journalist"], ["Mary", 30, "Programmer"], ["Abe", 40, "Chef"]]
df = pd.DataFrame(data=data)
df

      0   1           2
0  John  30  Journalist
1  Mary  30  Programmer
2   Abe  40        Chef

Recall that we create an object of a custom class like **`object = Class()`** . Since `DataFrame` is defined in `pandas` we use `pd.DataFrame()` .

#### **Adding Column Names**

The 0,1,2 colum names above are default values. To specify the column names we want, **`DataFrame`** has another attribute: `columns`

In [4]:
cols = ["Name", "Age", "Job"]
df = pd.DataFrame(data=data, columns=cols)
df

   Name  Age         Job
0  John   30  Journalist
1  Mary   30  Programmer
2   Abe   40        Chef

#####  **`Series`**

The other main data type that `pandas` provide is the [Series](https://pandas.pydata.org/docs/reference/api/pandas.Series.html). 

A `Series` is just one colum of the `DataFrame` .

We can select a `Series` in two ways:
1. **`df["column_name"]`**
2. **`df.column_name`**

Let's select the Age column below:

In [5]:
df['Age']

0    30
1    30
2    40
Name: Age, dtype: int64

It is preferred to use `df["column_name"]` to access a column. The `df.column_name` notation does not work well when there are spaces in the column name.

#### **dtypes**

If you look at the `Series` object above you can see `dtype: int64` .

In `pandas` dtypes, which is an abbreviation for data types, refers to the type of the values in the column.

We will next look at some of the methods and functionality that `DataFrame` and `Series` provide, but much like how object types determine what you can do with them, the **dtype** of a column determines what functionality we can do with it.

For example, we can take the average of a numeric column, but not a non-numeric one.

The **`dtypes`** of columns are specific to `pandas` , but the most common ones are very similar to the built-in Python types:
1. `object` is just text, which is similar to strings.
2. `int64` are integers
3. `float64` are float
4. `bool` are boolean

We can view the `dtypes` of every column in our `DataFrame` by accessing its `dtypes` attribute:

In [6]:
df.dtypes

Name    object
Age      int64
Job     object
dtype: object

#### **`Series`** Operations

We can use operations on `Series` of a certain dtype that are similar to the operations we can do with the dtype's similar built-in counterpart.

These operations act element-wise.

For example, we can add `int64` `Series` similarly to how we can add integer values in Python

In [7]:
df['Age'] + df['Age']

0    60
1    60
2    80
Name: Age, dtype: int64

We can use all basic integer operations here:

In [9]:
df['Age'] * 3 - 1

0     89
1     89
2    119
Name: Age, dtype: int64

##### **Selecting a value from a `Series`** 

Sometimes we will want to pull out a value in a `Series`. We can index into a `Series` similar to how we index into a list to pull out values:

In [10]:
df['Age'][0]

np.int64(30)

#### **Selecting a Subset of Columns**

We have seen how to select a given column as a `Series`.

We can also select a subset of columns as a `DataFrame`.

We can select a subset of columns like this:

`df[[col_1, col_2, col_3, ...]]`

Let's select only the Name and Age columns:

In [11]:
df[['Name', 'Age']]

   Name  Age
0  John   30
1  Mary   30
2   Abe   40